version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: mini_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mini_rabbit
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

  minio:
    image: minio/minio
    container_name: mini_minio
    restart: always
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: mini_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Aguardando MinIO...';
      sleep 5;
      mc alias set local http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};
      mc mb local/videos || true;
      mc anonymous set download local/videos;
      echo 'Bucket configurado como público';
      exit 0;
      "
  nginx:
    image: nginx:latest
    container_name: mini_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - minio
  app:
    build: .
    container_name: mini_app
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - minio
    ports:
      - "${APP_PORT}:8080"

volumes:
  postgres_data:
  minio_data:
