spring.application.name=${APP_NAME}

# Postgres
spring.datasource.url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MinIO
minio.url=http://minio:9000
minio.public-url=http://localhost
minio.bucket=${MINIO_BUCKET}
minio.access-key=${MINIO_USER}
minio.secret-key=${MINIO_PASSWORD}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Security
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION}

# Multipart
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
